spring:
  datasource:
    url: "jdbc:oracle:thin:@//localhost:3000/XEPDB1"
    username: "pdbadmin"
    password: "Rewind0614"
    driver-class-name: "oracle.jdbc.driver.OracleDriver"
  session:
    jdbc:
      table-name: "SPRING_SESSION"
      initialize-schema: always
